apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs-pv
  namespace: monitoring
  labels:
    type: nfs
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: rpi4-master
    path: "/data/public/grafana"
