apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-nfs-pv
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: rpi4-master
    path: "/data/public/docker-registry"
