apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-nfs-pvc
spec:
  storageClassName: storage-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
