apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-nfs-pvc
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: storage-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
