apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs-pv
  namespace: monitoring
  labels:
    type: nfs
    app: prometheus-deployment
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: rpi4-master
    path: "/data/public/prometheus"
