apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: buypass-production
spec:
  acme:
    email: adrianramosrp@gmail.com
    server: https://api.buypass.com/acme/directory
    preferredChain: "Buypass Class 2 Root CA"
    privateKeySecretRef:
      name: buypass-tls-key
    solvers:
    - http01:
        ingress:
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: traefik 
